### ISSUE TITLE
Update readme and remove unnecessary function from code

### ISSUE THREAD

**Issue by PatrickAlphaC** [gmondok/avaxLinkFeeds#1]
1. Update readme:
Right now, it's unclear where/how I should be deploying this code. A user should be able to walk down the readme and be able to follow along perfectly. I'm assuming you'd like them to deploy this using remix, please add a link to remix that will populate the code, and lay out the steps in a:
1.
2.
3.
Type manner.

2. Point to the documentation 
This demo is supplementary to the docs, please point to the docs where you're getting both the code from, and the price feed address from.

3. Remove `getAvaxPrice`, `int public price;`, and change the visibility of `getLatestPrice` to public.
Fuji is sometimes a little slow, which is why you probably didn't see an update when you called `getLatestPrice`. Please just keep `getLatestPrice` and make it public.

4. solidity pragma
Ideally use version 8

**Comment by gmondok** [comment]
@PatrickAlphaC 
1) There's an article accompanying this, with a remix link
2) The article links to the docs
3) I don't think we want to release a demo where they request the price and get nothing. Putting it in a public variable rather than a return fixed that.
4) Will update.

**Comment by PatrickAlphaC** [comment]
1. Every piece of content we make should be strong enough to stand on it's own. Please have the README be able to teach a user quickly how to spin up and use this repo.
2. Same as above
3. They shouldn't be calling the `price` variable, they should be calling `getLatestPrice`. Please see me if this doesn't make sense. 

Additional:
- By convention, contract names and files should be capitalized: avaxLinkFeeds.sol -> AvaxLinkFeeds.sol

**Comment by gmondok** [comment]
Readme updated, made it match the docs, capitalized filename.
